package com.lijeeshk.paso.core;

/**
 * Created by lijeesh on 19/12/15.
 */
public enum Phase {

    PRE_AUTHENTICATION,
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_FAILURE,
    PRE_SERVICE_MATCH,
    SERVICE_MATCH_SUCCESS,
    SERVICE_MATCH_FAILURE,
    PRE_AUTHORIZATION,
    AUTHORIZATION_SUCCESS,
    AUTHORIZATION_FAILURE,
    PRE_SERVICE_DISPATCH,
    DISPATCH_SUCCESS,
    DISPATCH_FAILURE,
    FILTER_FAILED,


    SERVICE_RESPONSE_SUCCESS,
    SERVICE_RESPONSE_FAILURE,
    PRE_RESPONSE_FLUSH,
    POST_RESPONSE_FLUSH,
}
